name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [7.1, 7.2, 7.3]
        include:
          - php_version: 7.3
            latest: true
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vbyndych/oro-docker-php:${{ matrix.php_version }} --build-arg PHP_VERSION=${{ matrix.php_version }}
    - name: Tag latest version
      if: matrix.latest
      run: docker tag vbyndych/oro-docker-php:${{ matrix.php_version }} vbyndych/oro-docker-php:latest
    - name: Scan image
      uses: anchore/scan-action@master
      with:
        image-reference: "vbyndych/oro-docker-php:${{ matrix.php_version }}"
        fail-build: true
        include-app-packages: true
    - name: ZIP Image Scan results
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./scan-report.zip ./anchore-reports
    - name: Upload Image Scan results
      uses: actions/upload-artifact@v1
      with:
        name: sacn-report-${{ matrix.php_version }}
        path: scan-report.zip
    - name: Login to DockerHub Registry
      run: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.GITHUB_DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_DOCKER_PASSWORD }}
    - name: Push image to Dockerhub
      run: docker push vbyndych/oro-docker-php:${{ matrix.php_version }}
    - name: Push latest image to Dockerhub
      if: matrix.latest
      run: docker push vbyndych/oro-docker-php:latest
