name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [7.1, 7.2, 7.3]
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vbyndych/oro-docker-php:${{ matrix.php_version }} --build-arg PHP_VERSION=${{ matrix.php_version }}
    - name: Login to GitHub Docker Registry
      run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.GITHUB_DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_DOCKER_PASSWORD }}
    - name: Push image to Dockerhub
      run: docker push vbyndych/oro-docker-php:${{ matrix.php_version }}
